steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/practice-projects-420709/flask/flask-continuous-deployment:0b259d7', '.']

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/practice-projects-420709/flask/flask-continuous-deployment:0b259d7']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud beta run deploy continuous-deployment-trial \
            --region=europe-west1 \
            --platform=managed \
            --image=gcr.io/practice-projects-420709/flask/flask-continuous-deployment:0b259d7 \
            --allow-unauthenticated
